apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  source:
    path: jenkins
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  ignoreDifferences:
  - group: ''
    jsonPointers:
    - /data/jenkins-admin-password
    kind: Secret
