apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          args:
            - server
            - --namespaced
            - --auth-mode=sso
            - --auth-mode=client
            - --x-frame-options=SAMEORIGIN
