apiVersion: v1
data:
  # https://github.com/settings/applications/1416526
  config: |
    sso:
      issuer: https://dex.apps.argoproj.io/dex
      clientId:
        name: argo-server-sso
        key: clientID
      clientSecret:
        name: argo-server-sso
        key: clientSecret
      redirectUrl: https://workflows.apps.argoproj.io/oauth2/callback
      scopes:
       - groups
      rbac:
        enabled: true
    workflowDefaults:
      spec:
        activeDeadlineSeconds: 600
    retentionPolicy:
      completed: 20
      failed: 3
      errored: 3
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
