kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reaper
rules:
- apiGroups: [""]
  resources: ["pods", ]
  verbs: ["get", "delete", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]